name: Child Job
on:
  workflow_call:
    inputs:
      name:
        description: "Your Name"
        required: true
        type: string
        default: "sid"

jobs:
  validate_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Validate Inputs
        run: |
          if [[ ${{ github.events.inputs.name }} != "sid" ]]; then
            echo "Invalid input"
            exit 1
          fi

          echo "Valid inputs"
  
  create-env:
    runs-on: ubuntu-latest
    needs: validate_inputs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create Environment
        run: |
          echo "Installing python"
          sudo apt update -yqq
          sudo apt install python3 python3-pip python3.10-venv -yqq

          #Activate env
          python3 -m venv .venv
          source .venv/bin/activate
          python --version
      
      - name: Upload Venv
        uses: actions/upload-artifact@v2
        with:
          name: python-venv
          path: .venv
      