name: Parent Job
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Your Name"
        required: true
        type: string
        default: "sid"

jobs:
  call-child:
    uses: ./.github/workflows/dependent.yml
    with:
      name: ${{ github.event.inputs.name }}

  build:
    runs-on: ubuntu-latest
    needs: call-child
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Virtual Environment
        uses: actions/download-artifact@v4
        with:
          name: python-venv
          path: venv-artifact/

      - name: Restore Virtual Environment
        run: |
          mkdir -p .venv
          mv venv-artifact/* .venv/
          ls -la .venv  # Verify contents

      - name: Activate Virtual Environment
        run: |
          source .venv/bin/activate
          python --version
